### ISSUE TITLE
Not working for thread dumps generated by intellij and VisualVM

### ISSUE THREAD

**Issue by sureshg** [igr/tdv#5]
Getting all sort of error parsing thread dump (using `v0.5.0`) generated by IntelliJ and VisualVM.

```
Generating report for tdump.txt.tdump
Exception in thread "main" java.lang.IllegalStateException: Invalid system thread header: 2024-03-25 16:47:01 at
[tdi] 0: 2024-03-25 16:47:01
[tdi] 1: Full thread dump OpenJDK 64-Bit Server VM (21.0.2+13-LTS mixed mode, sharing):
[tdi] 2:
        at dev.oblac.tdv.parser.ParseThread.parseSystemThread(ParseThread.kt:63)
        at dev.oblac.tdv.parser.ParseThread.invoke(ParseThread.kt:19)
        at dev.oblac.tdv.parser.ParseThreadDump.invoke(ParseThreadDump.kt:39)
        at dev.oblac.tdv.app.ParseKt.parseThreadDumpReport(parse.kt:19)
        at dev.oblac.tdv.app.AppKt.generateThreadDumpReport(App.kt:29)
        at dev.oblac.tdv.app.RunCommand.run(App.kt:18)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:279)

```

```
Generating report for tdump.txt.tdump
Exception in thread "main" java.lang.IllegalStateException: Invalid system thread header: 0x0000000146811000, 0x0000000134017800, 0x000000013401a200, 0x000000013401aa00, at
[tdi] 4: 0x0000000146811000, 0x0000000134017800, 0x000000013401a200, 0x000000013401aa00,
[tdi] 5: 0x0000000133808600, 0x0000000143809000, 0x000000014580bc00, 0x000000014580c400,
[tdi] 6: 0x000000014380b200, 0x0000000144816c00, 0x0000000145a47000, 0x0000000143950800,
        at dev.oblac.tdv.parser.ParseThread.parseSystemThread(ParseThread.kt:63)
        at dev.oblac.tdv.parser.ParseThread.invoke(ParseThread.kt:19)
        at dev.oblac.tdv.parser.ParseThreadDump.invoke(ParseThreadDump.kt:39)
        at dev.oblac.tdv.app.ParseKt.parseThreadDumpReport(parse.kt:19)
        at dev.oblac.tdv.app.AppKt.generateThreadDumpReport(App.kt:29)
        at dev.oblac.tdv.app.RunCommand.run(App.kt:18)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:279)
```
[tdump.txt](https://github.com/igr/tdv/files/14750646/tdump.txt)

```
❯ tdv threads_report.txt
Generating report for threads_report.txt
Exception in thread "main" java.lang.IllegalStateException: Invalid system thread header: "RMI TCP Connection(3)-127.0.0.1" prio=0 tid=0x0 nid=0x0 runnable at
[tdi] 0: "RMI TCP Connection(3)-127.0.0.1" prio=0 tid=0x0 nid=0x0 runnable
[tdi] 1:      java.lang.Thread.State: RUNNABLE
[tdi] 2:        at java.management@17.0.10/sun.management.ThreadImpl.dumpThreads0(Native Method)
        at dev.oblac.tdv.parser.ParseThread.parseSystemThread(ParseThread.kt:63)
        at dev.oblac.tdv.parser.ParseThread.invoke(ParseThread.kt:19)
        at dev.oblac.tdv.parser.ParseThreadDump.invoke(ParseThreadDump.kt:39)
        at dev.oblac.tdv.app.ParseKt.parseThreadDumpReport(parse.kt:19)
        at dev.oblac.tdv.app.AppKt.generateThreadDumpReport(App.kt:29)
        at dev.oblac.tdv.app.RunCommand.run(App.kt:18)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:279)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:41)
```

[threads_report.txt](https://github.com/igr/tdv/files/14750659/threads_report.txt)

**Comment by igr** [comment]
I have fixed the first issue.

However, the second thread dump has very little information. Threads do not have IDs etc, so there is nothing much to analyse besides the simple count.

**Comment by igr** [comment]
I will close the issue and open a new one with the second thread dump. However, I am not sure if that one makes sense to be analyzed.
